baseurl = "/"
languageCode = "zh-CN"
title = "Blurred code"
theme = "hugo-classic"
googleAnalytics = "UA-71864552-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage =  true
enableRobotsTXT =   true
enableGitInfo = true
pygmentsCodeFences = false

[permalinks]
    post = "/:year/:month/:slug/"

 [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "自豪的采用 [Hugo](https://gohugo.io/) | [hugo-classic](https://github.com/goodroot/hugo-classic) | panda[at]blurredcode.com"
    custom_css = ["css/theme-override.css"]
[markup]
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark.renderer]
      unsafe= true
[frontmatter]
date = ["lastmod","updated",":git","date",":fileModTime",":default"]

[params.utter]
enable = true
repo = "BlurryLight/BlurryLight.github.io"
issueTerm = "title"
theme = "github-light"
