name: github pages

on:
  push:
    branches:
      - pages-src
env:
  OSS_ENDPOINT: ${{secrets.OSS_ENDPOINT}}
  OSS_KEY_ID: ${{secrets.OSS_KEY_ID}}
  OSS_KEY_SECRET: ${{secrets.OSS_KEY_SECRET}}
  OSS_BUCKET_NAME: ${{secrets.OSS_BUCKET_NAME}}
  HUGO_PARAMS_CDN_enable: true
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
